public enum Location {
    FARM,
    WORLDMAP,
    POND,
    MOUNTAIN_LAKE,
    FOREST_RIVER,
    OCEAN,
    MAYOR_TADI_HOUSE,
    CAROLINE_HOUSE,
    PERRY_HOUSE,
    DASCO_HOUSE,
    ABIGAIL_HOUSE,
    STORE;
}
